server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sudongk/config-data.git
#          username: Sudongk
#          password: git access token
encrypt:
  key: encryptkey
